CSV support for Tyme2
clesquir/timesheet-integration pull request #1
Opened 2020-12-02 13:06 UTC by spoulin

2020-12-02 17:45 UTC, clesquir requested changes

2020-12-02 17:45 UTC, clesquir commented on src/Infrastructure/Messaging/Command/ImportCSVToTimesheetHandler.php
> +		$this->bus->handle(new ImportCSVToTimesheetCommand($entries, $command->dryRun()));
That should still be `ImportTimeEntriesToTimesheetCommand`

2020-12-02 17:45 UTC, clesquir commented on src/Application/Console/ImportCSVToTimesheetConsole.php
> +		$this->bus->handle(new ImportCSVToTimesheetCommand($date, $dryRun));
I would get rid of everything with dates since your CSV will be imported regardless this parameter (right?)

2020-12-02 17:45 UTC, clesquir commented on src/Infrastructure/Messaging/Command/ImportCSVToTimesheetCommand.php
> +	private DateTimeImmutable $date;
Same comment: I would get rid of everything with dates since your CSV will be imported regardless this parameter (right?)

2020-12-02 20:52 UTC, spoulin23 commented on src/Application/Console/ImportCSVToTimesheetConsole.php
> +		$this->bus->handle(new ImportCSVToTimesheetCommand($date, $dryRun));
I changed the date argument to a filename one.

2020-12-09 16:49 UTC, clesquir approved these changes

2020-12-09 16:50 UTC, merged